# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 04:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_project', '0003_auto_20171017_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessrecord',
            name='ids',
        ),
    ]
